<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
      <!-- Disable hashed file names -->
  <StaticWebAssetFingerprintingEnabled>false</StaticWebAssetFingerprintingEnabled>
  <!-- Disable .br / .gz files -->
  <BlazorEnableCompression>false</BlazorEnableCompression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.5" PrivateAssets="all" />
    <PackageReference Include="Syncfusion.Blazor.Grid" Version="33.1.49" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="33.1.49" />
  </ItemGroup>

</Project>
